# PolyPy Web + Python unified — Thonny IDE, MicroPython or standard Python

import dytx
import dytx.web as dxw

dytx.init(mode="python", ide="thonny")

def define_web_header():
    """
    #html: <html><head><title>PolyPy Proof of Work</title></head><body>
    #html: <h1>Built with PolyPy + DYTX</h1>
    #html: </body></html>
    """
    pass

def on_button_click():
    """
    #javascript: document.getElementById('btn').addEventListener('click', () => {
    #javascript:   console.log('PolyPy button clicked!');
    #javascript: });
    """
    pass

# DYTX parses the #html: and #javascript: comments and generates output files
dxw.compile(define_web_header, output="index.html")
dxw.compile(on_button_click, output="app.js")
print("Proof of Work #3 Complete: index.html and app.js generated by DYTX")
